apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bank-app.fullname" . }}
  labels:
    {{- include "bank-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bank-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bank-app.selectorLabels" . | nindent 8 }}
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "bank-app-role"
        vault.hashicorp.com/agent-inject-secret-redis-config: "secret/data/redis-config"
        vault.hashicorp.com/agent-inject-template-redis-config: |
          {{ `{{- with secret "secret/data/redis-config" -}}
          {{ .Data.data.password }}
          {{- end -}}` }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: default
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: REDIS_ADDR
              value: {{ .Values.env.REDIS_ADDR | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http